# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - CSS
  - EDITORCONFIG
  - JAVASCRIPT
ENABLE_LINTERS:
  - JAVA_CHECKSTYLE
PRINT_ALL_FILES: false
JAVA_CHECKSTYLE_FILE_EXTENSIONS:
  - ".java"
JAVA_CHECKSTYLE_FILE_NAME: "checkstyle-config.xml"
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.github/workflows|TEMPLATES)'
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '(\.automation/generated|docs/descriptors)'
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
JSON_REPORTER: true
TEXT_REPORTER: true
PRINT_ALPACA: false